services:
  - type: web
    name: colorfixmatch
    env: python
    plan: free
    region: frankfurt
    branch: master

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3

    autoDeploy: true